spring.application.name=spring-boot-rest-jpa-aop-logging
server.port=9090

# SpringDoc / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method
